In [ ]:
!pip install pycaret
!pip install shap #interpret_model 사용시 필요

     |████████████████████████████████| 288 kB 7.0 MB/s 
     |████████████████████████████████| 6.8 MB 88.8 MB/s 
     |████████████████████████████████| 1.7 MB 81.9 MB/s 
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
    Preparing wheel metadata ... done
     |████████████████████████████████| 1.3 MB 64.2 MB/s 
     |████████████████████████████████| 56 kB 5.1 MB/s 
     |████████████████████████████████| 167 kB 67.7 MB/s 
     |████████████████████████████████| 2.0 MB 58.5 MB/s 
     |████████████████████████████████| 113 kB 90.8 MB/s 
     |████████████████████████████████| 86 kB 7.6 MB/s 
     |████████████████████████████████| 261 kB 71.5 MB/s 
     |████████████████████████████████| 15.5 MB 27.0 MB/s 
     |████████████████████████████████| 675 kB 61.5 MB/s 
     |████████████████████████████████| 303 kB 69.9 MB/s 
     |████████████████████████████████| 3.1 MB 50.0 MB/s 
     |█████████████████

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
from sklearn.metrics import confusion_matrix

def draw_matrix(data):
  print(confusion_matrix(data['LABEL'],data['Anomaly']))

In [ ]:
import numpy as np
import pandas as pd
#from pycaret.classification import *

cloud_path = '/content/drive/MyDrive/0.competition/dataset/'

path = cloud_path

labeled = pd.read_csv(path + 'cn7_labeled.csv',index_col=0)
unlabeled = pd.read_csv(path + 'cn7_unlabeled.csv', index_col=0)

In [ ]:
labeled

LABEL  Injection_Time  ...  Mold_Temperature_3  Mold_Temperature_4
0         0            9.59  ...           24.799999           27.500000
1         0            9.60  ...           24.799999           27.600000
4         0            9.59  ...           25.000000           27.600000
5         0            9.58  ...           25.000000           27.600000
7         0            9.58  ...           25.000000           27.600000
...     ...             ...  ...                 ...                 ...
7987      0            9.58  ...           21.000000           22.400000
7989      0            9.60  ...           21.000000           22.400000
7991      0            9.60  ...           21.000000           22.400000
7993      0            9.60  ...           21.000000           22.400000
7994      0            9.60  ...           21.000000           22.299999

[6736 rows x 25 columns]

In [ ]:
labeled_data = labeled.sample(frac=0.99, random_state=2021)
labeled_unseen_data = labeled.drop(labeled_data.index)

labeled_data.reset_index(drop=True, inplace=True)
labeled_unseen_data.reset_index(drop=True, inplace=True)

print('Data for Modeling: ' + str(labeled_data.shape))
print('Unseen Data For Predictions: ' + str(labeled_unseen_data.shape))

Data for Modeling: (6669, 25)
Unseen Data For Predictions: (67, 25)


In [ ]:
from pycaret.anomaly import *

data = setup(labeled_data, normalize = True, session_id=1)

Description                 Value
0                               session_id                     1
1                            Original Data            (6669, 25)
2                           Missing Values                 False
3                         Numeric Features                    23
4                     Categorical Features                     2
5                         Ordinal Features                 False
6                High Cardinality Features                 False
7                  High Cardinality Method                  None
8                         Transformed Data            (6669, 27)
9                                 CPU Jobs                    -1
10                                 Use GPU                 False
11                          Log Experiment                 False
12                         Experiment Name  anomaly-default-name
13                                     USI                  a615
14                         Imputation Type                simple
15          Iterative Imputation Iteration                  None
16                         Numeric Imputer                  mean
17      Iterative Imputation Numeric Model                  None
18                     Categorical Imputer                  mode
19  Iterative Imputation Categorical Model                  None
20           Unknown Categoricals Handling        least_frequent
21                               Normalize                  True
22                        Normalize Method                zscore
23                          Transformation                 False
24                   Transformation Method                  None
25                                     PCA                 False
26                              PCA Method                  None
27                          PCA Components                  None
28                     Ignore Low Variance                 False
29                     Combine Rare Levels                 False
30                    Rare Level Threshold                  None
31                         Numeric Binning                 False
32                         Remove Outliers                 False
33                      Outliers Threshold                  None
34                Remove Multicollinearity                 False
35             Multicollinearity Threshold                  None
36             Remove Perfect Collinearity                 False
37                              Clustering                 False
38                    Clustering Iteration                  None
39                     Polynomial Features                 False
40                       Polynomial Degree                  None
41                    Trignometry Features                 False
42                    Polynomial Threshold                  None
43                          Group Features                 False
44                       Feature Selection                 False
45                Feature Selection Method               classic
46            Features Selection Threshold                  None
47                     Feature Interaction                 False
48                           Feature Ratio                 False
49                   Interaction Threshold                  None

In [ ]:
models()

Name                    Reference
ID                                                                       
abod            Angle-base Outlier Detection        pyod.models.abod.ABOD
cluster       Clustering-Based Local Outlier      pyod.models.cblof.CBLOF
cof         Connectivity-Based Local Outlier          pyod.models.cof.COF
iforest                     Isolation Forest  pyod.models.iforest.IForest
histogram  Histogram-based Outlier Detection        pyod.models.hbos.HBOS
knn             K-Nearest Neighbors Detector          pyod.models.knn.KNN
lof                     Local Outlier Factor          pyod.models.lof.LOF
svm                   One-class SVM detector      pyod.models.ocsvm.OCSVM
pca             Principal Component Analysis          pyod.models.pca.PCA
mcd           Minimum Covariance Determinant          pyod.models.mcd.MCD
sod               Subspace Outlier Detection          pyod.models.sod.SOD
sos             Stochastic Outlier Selection          pyod.models.sos.SOS

In [ ]:
#abod는 구렸다 패스
cluster = create_model('cluster')
cof = create_model('cof')
iforest = create_model('iforest')
histogram = create_model('histogram')
knn = create_model('knn')
lof = create_model('lof')
svm = create_model('svm', fraction = 0.025)
pca = create_model('pca')
mcd = create_model('mcd')
sod = create_model('sod')
sos = create_model('sos')

In [ ]:
print(cluster)
print(cof)
print(iforest)
print(histogram)
print(knn)
print(lof)
print(svm)
print(pca)
print(mcd)
print(sod)
print(sos)

CBLOF(alpha=0.9, beta=5, check_estimator=False, clustering_estimator=None,
   contamination=0.05, n_clusters=8, n_jobs=None, random_state=1,
   use_weights=False)
COF(contamination=0.05, method='fast', n_neighbors=None)
IForest(behaviour='new', bootstrap=False, contamination=0.05,
    max_features=1.0, max_samples='auto', n_estimators=100, n_jobs=-1,
    random_state=1, verbose=0)
HBOS(alpha=0.1, contamination=0.05, n_bins=10, tol=0.5)
KNN(algorithm='auto', contamination=0.05, leaf_size=30, method='largest',
  metric='minkowski', metric_params=None, n_jobs=-1, n_neighbors=5, p=2,
  radius=1.0)
LOF(algorithm='auto', contamination=0.05, leaf_size=30, metric='minkowski',
  metric_params=None, n_jobs=-1, n_neighbors=20, novelty=True, p=2)
OCSVM(cache_size=200, coef0=0.0, contamination=0.025, degree=3, gamma='auto',
   kernel='rbf', max_iter=-1, nu=0.5, shrinking=True, tol=0.001,
   verbose=False)
PCA(contamination=0.05, copy=True, iterated_power='auto', n_components=None,
  n_selected_comp

In [ ]:
cluster_results = assign_model(cluster)
cof_results = assign_model(cof)
iforest_results = assign_model(iforest)
hist_results = assign_model(histogram)
knn_results = assign_model(knn)
lof_results = assign_model(lof)
svm_results = assign_model(svm)
pca_results = assign_model(pca)
mcd_results = assign_model(mcd)
sod_results = assign_model(sod)
sos_results = assign_model(sos)

cluster_res = predict_model(cluster, data = labeled_data)
cof_res = predict_model(cof, data = labeled_data)
iforest_res = predict_model(iforest, data = labeled_data)
hist_res = predict_model(histogram, data = labeled_data)
knn_res = predict_model(knn, data = labeled_data)
lof_res = predict_model(lof, data = labeled_data)
svm_res = predict_model(svm, data = labeled_data)
pca_res = predict_model(pca, data = labeled_data)
mcd_res = predict_model(mcd, data = labeled_data)
#sod_res = predict_model(sod, data = labeled_data)
#sos_res = predict_model(sos, data = labeled_data)

print("cluster")
draw_matrix(cluster_res)
print("cof")
draw_matrix(cof_res)
print("iforest")
draw_matrix(iforest_res)
print("knn")
draw_matrix(knn_res)
print("lof")
draw_matrix(lof_res)
print("svm")
draw_matrix(svm_res)
print("pca")
draw_matrix(pca_res)
print("mcd")
draw_matrix(mcd_res)
# print("sod")
# draw_matrix(sod_res)
# print("sos")
# draw_matrix(sos_res)

# print("=" * 50)

# rest_if = predict_model(iforest, data=labeled_unseen_data)
# rest_svm = predict_model(svm, data = labeled_unseen_data)
# rest_abod = predict_model(abod, data = labeled_unseen_data)
# rest_knn = predict_model(knn, data = labeled_unseen_data)

# draw_matrix(rest_if)
# draw_matrix(rest_svm)
# draw_matrix(rest_abod)
# draw_matrix(rest_knn)

cluster
[[6324  306]
 [  13   26]]
cof
[[6336  294]
 [   0   39]]
iforest
[[6333  297]
 [   2   37]]
knn
[[6341  289]
 [   0   39]]
lof
[[6377  253]
 [   0   39]]
svm
[[6501  129]
 [   2   37]]
pca
[[6334  296]
 [   0   39]]
mcd
[[6328  302]
 [   7   32]]


In [ ]:
tuned_svm = tune_model(svm, supervised_target = 'LABEL')

Accuracy     AUC  Recall  Prec.      F1   Kappa     MCC
0.00    0.9975  0.9803  0.5194    1.0  0.6716  0.6705  0.7126
0.01    0.9981  0.9821  0.6376    1.0  0.7711  0.7702  0.7934
0.02    0.9981  0.9842  0.6376    1.0  0.7711  0.7702  0.7934
0.03    0.9981  0.9845  0.6376    1.0  0.7711  0.7702  0.7934
0.04    0.9981  0.9831  0.6376    1.0  0.7711  0.7702  0.7934
0.05    0.9981  0.9827  0.6376    1.0  0.7711  0.7702  0.7934
0.06    0.9981  0.9816  0.6376    1.0  0.7711  0.7702  0.7934
0.07    0.9981  0.9822  0.6376    1.0  0.7711  0.7702  0.7934
0.08    0.9981  0.9819  0.6376    1.0  0.7711  0.7702  0.7934
0.09    0.9981  0.9821  0.6376    1.0  0.7711  0.7702  0.7934
0.10    0.9981  0.9819  0.6376    1.0  0.7711  0.7702  0.7934

In [ ]:
tuned_pca = tune_model(pca, supervised_target = 'LABEL')

Accuracy     AUC  Recall  Prec.      F1   Kappa     MCC
0.00    0.9976  0.9803  0.5671    1.0  0.7158  0.7147  0.7476
0.01    0.9980  0.8695  0.1667    0.4  0.2333     NaN  0.2566
0.02    0.9986  0.6820  0.0000    0.0  0.0000     NaN  0.0000
0.03    0.9991  0.4903  0.0000    0.0  0.0000     NaN  0.0000
0.04    0.9994  0.2928  0.0000    0.0  0.0000     NaN  0.0000
0.05    0.9995  0.1963  0.0000    0.0  0.0000     NaN  0.0000
0.06    0.9997  0.1998  0.0000    0.0  0.0000     NaN  0.0000
0.07    0.9997  0.1998  0.0000    0.0  0.0000     NaN  0.0000
0.08    0.9997  0.1998  0.0000    0.0  0.0000     NaN  0.0000
0.09    0.9997  0.1998  0.0000    0.0  0.0000     NaN  0.0000
0.10    0.9997  0.1997  0.0000    0.0  0.0000     NaN  0.0000

In [ ]:
tuned_iforest = tune_model(iforest, supervised_target='LABEL', fold=5)

Accuracy     AUC  Recall  Prec.      F1   Kappa     MCC
0.00    0.9975  0.9803  0.5194    1.0  0.6716  0.6705  0.7126
0.01    0.9980  0.9620  0.1167    0.4  0.1800  0.1797  0.2153
0.02    0.9982  0.9626  0.0000    0.0  0.0000  0.0000  0.0000
0.03    0.9986  0.9732  0.0000    0.0  0.0000  0.0000  0.0000
0.04    0.9986  0.9773  0.0000    0.0  0.0000  0.0000  0.0000
0.05    0.9991  0.5917  0.0000    0.0  0.0000     NaN  0.0000
0.06    0.9990  0.5926  0.0000    0.0  0.0000     NaN  0.0000
0.07    0.9992  0.3956  0.0000    0.0  0.0000     NaN  0.0000
0.08    0.9993  0.3772  0.0000    0.0  0.0000     NaN  0.0000
0.09    0.9993  0.3778  0.0000    0.0  0.0000     NaN  0.0000
0.10    0.9995  0.3901  0.0000    0.0  0.0000     NaN  0.0000

In [ ]:
print(tuned_iforest)

print(iforest)

IForest(behaviour='new', bootstrap=False, contamination=0.1, max_features=1.0,
    max_samples='auto', n_estimators=100, n_jobs=-1, random_state=1,
    verbose=0)
IForest(behaviour='new', bootstrap=False, contamination=0.05,
    max_features=1.0, max_samples='auto', n_estimators=100, n_jobs=-1,
    random_state=1, verbose=0)


In [ ]:
tuned_iforest2 = tune_model(model = 'iforest', supervised_target = 'LABEL', method = 'surrogate', fold = 5, verbose = True)

Accuracy     AUC  Recall  Prec.      F1   Kappa     MCC
0.00    0.9975  0.9803  0.5194    1.0  0.6716  0.6705  0.7126
0.01    0.9975  0.9812  0.5194    1.0  0.6716  0.6705  0.7126
0.02    0.9975  0.9829  0.5194    1.0  0.6716  0.6705  0.7126
0.03    0.9975  0.9862  0.5194    1.0  0.6716  0.6705  0.7126
0.04    0.9975  0.9835  0.5194    1.0  0.6716  0.6705  0.7126
0.05    0.9975  0.9858  0.5194    1.0  0.6716  0.6705  0.7126
0.06    0.9975  0.9846  0.5194    1.0  0.6716  0.6705  0.7126
0.07    0.9975  0.9848  0.5194    1.0  0.6716  0.6705  0.7126
0.08    0.9975  0.9854  0.5194    1.0  0.6716  0.6705  0.7126
0.09    0.9975  0.9843  0.5194    1.0  0.6716  0.6705  0.7126
0.10    0.9975  0.9847  0.5194    1.0  0.6716  0.6705  0.7126